// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZElrOFm0LKdIpJfZlFMyyxfSDL4wJogw',
    appId: '1:796405165831:web:8b3c31592fab3b42a69fa2',
    messagingSenderId: '796405165831',
    projectId: 'robanohashi-9387d',
    authDomain: 'robanohashi-9387d.firebaseapp.com',
    storageBucket: 'robanohashi-9387d.appspot.com',
    measurementId: 'G-E21S80MLEY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6EAnJzNtDAECEhzwX98kH-SJlIJhPcpE',
    appId: '1:796405165831:android:d37593993838a9aaa69fa2',
    messagingSenderId: '796405165831',
    projectId: 'robanohashi-9387d',
    storageBucket: 'robanohashi-9387d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2zhNY-I334i1l3z_MaztN4bsz4Z9yJt8',
    appId: '1:796405165831:ios:c8487a301a5023fca69fa2',
    messagingSenderId: '796405165831',
    projectId: 'robanohashi-9387d',
    storageBucket: 'robanohashi-9387d.appspot.com',
    androidClientId: '796405165831-trdove876j8ipf3roettu24ug81htcji.apps.googleusercontent.com',
    iosClientId: '796405165831-vv2nr9cq6phns7l78tbu3nclrlu7ji37.apps.googleusercontent.com',
    iosBundleId: 'com.example.robanohashi',
  );
}
