// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABNSkB1bXuD-ViwedtLUJyO7ZAkrTaDrc',
    appId: '1:922925388033:web:e15be6291c4ab3931e0b00',
    messagingSenderId: '922925388033',
    projectId: 'robanohashi-39c60',
    authDomain: 'robanohashi-39c60.firebaseapp.com',
    storageBucket: 'robanohashi-39c60.appspot.com',
    measurementId: 'G-H6F94PH5SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK5zT0VDmDjBH4XFixe2VX3KYKe8W4U_E',
    appId: '1:922925388033:android:9bf44ac5f04fe7bd1e0b00',
    messagingSenderId: '922925388033',
    projectId: 'robanohashi-39c60',
    storageBucket: 'robanohashi-39c60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtwaM62wagPxBYNslvVS2DNHLCFYw273w',
    appId: '1:922925388033:ios:a93ca2db6d12866e1e0b00',
    messagingSenderId: '922925388033',
    projectId: 'robanohashi-39c60',
    storageBucket: 'robanohashi-39c60.appspot.com',
    androidClientId: '922925388033-fs9aamrm9n730813b10uklqm23ujp09n.apps.googleusercontent.com',
    iosClientId: '922925388033-t0rlgc3n88qb55704kafn8nf04eah6et.apps.googleusercontent.com',
    iosBundleId: 'com.example.robanohashi',
  );
}
